name: Baixar Rankings
on:
  schedule:
    # Executa todo dia às 12h UTC (09h no Brasil)
    - cron: '0 12 * * *'
  # Permite execução manual
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona o repositório
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Instala o R
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      # 3. Instala o pacote crypto2
      - name: Instalar dependências R
        run: |
          Rscript -e 'install.packages("crypto2", repos="https://cloud.r-project.org")'

      # 4. Executa o script que baixa e salva o ranking
      - name: Executar download de rankings
        run: |
          Rscript R/download_crypto_rankings.R

      # 5. Faz upload dos arquivos gerados como artefato
      - name: Upload de artefatos
        uses: actions/upload-artifact@v2
        with:
          name: rankings
          path: DB/CMK/

