name: Daily Crypto Rankings Scrape

on:
  # Executa todo dia às 12 h UTC (09 h BRT)
  schedule:
    - cron: '0 12 * * *'
  # Permite disparar manualmente
  workflow_dispatch:

# Precisamos gravar no repositório (commit)
permissions:
  contents: write

jobs:
  scrape_data:
    runs-on: ubuntu-latest

    steps:
    # 1) Checkout com histórico completo
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # 2) Bibliotecas de sistema para {curl}/{openssl}
    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends \
          libcurl4-openssl-dev libssl-dev libxml2-dev

    # 3) Instalar R
    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    # 4) Instalar pacote necessário
    - name: Install required R packages
      run: |
        Rscript -e 'install.packages("crypto2", repos="https://cran.rstudio.com/")'

    # 5) (Opcional) checar se instalou
    - name: Check installed package
      run: |
        Rscript -e 'if (!requireNamespace("crypto2", quietly = TRUE)) stop("Pacote crypto2 não instalado")'

    # 6) Executar o script que gera o ranking
    - name: Run Crypto Rankings script
      run: |
        Rscript R/download_crypto_rankings.R

    # 7) Preparar autenticação Git para commit
    - name: Set up Git authentication
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

    # 8) Configurar usuário do commit
    - name: Configure git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    # 9) Commit & push dos novos arquivos .rds
    - name: Commit and push changes
      run: |
        git add DB/CMK/*.rds
        git commit -m "Atualização diária do ranking de criptomoedas: $(date +'%Y-%m-%d')" || echo "Nada para commitar"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
