name: Crypto Rankings (CoinMarketCap)

on:
  # Executa manualmente ou em cron diário (12 h UTC = 09 h BRT)
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  rankings:
    runs-on: ubuntu-latest

    # Permissões mínimas recomendadas
    permissions:
      contents: read        # para checkout
      id-token: write       # exigido pelo setup‑r

    steps:
      # 1) Baixar o código
      - name: Checkout repositório
        uses: actions/checkout@v4

      # 2) Instalar R (r-lib/actions)
      - name: Configurar R 4.3
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3'  # escolha da versão

      # 3) Instalar dependências de sistema para pacotes R que usam {curl}/{openssl}
      - name: Instalar bibliotecas do sistema
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev libssl-dev libxml2-dev

      # 4) Instalar pacote R necessário
      - name: Instalar pacotes R
        run: |
          Rscript -e "install.packages('crypto2', repos = 'https://cloud.r-project.org')"

      # 5) Executar o script que baixa e salva o ranking
      - name: Executar script de download
        run: |
          Rscript R/download_crypto_rankings.R

      # 6) Fazer upload dos arquivos .rds gerados
      - name: Upload de artefatos
        uses: actions/upload-artifact@v2
        with:
          name: rankings
          path: DB/CMK/
