name: Nion

on:
  schedule:
    # todo dia às 12h UTC (09h BRT)
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      # 1) checkout do código
      - name: Checkout
        uses: actions/checkout@v3

      # 2) setup do R (observe o caminho completo “actions/setup-r”)
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      # 3) instalar o pacote crypto2
      - name: Instalar dependências R
        run: |
          Rscript -e 'install.packages("crypto2", repos="https://cloud.r-project.org")'

      # 4) rodar o script de download
      - name: Executar download de rankings
        run: |
          Rscript R/download_crypto_rankings.R

      # 5) fazer upload dos .rds gerados
      - name: Upload de artefatos
        uses: actions/upload-artifact@v2
        with:
          name: rankings
          path: DB/CMK/
