name: Baixar Rankings de Criptomoedas

on:
  schedule:
    - cron: '0 12 * * *' # Executa todo dia às 12h UTC (09h no Brasil)
  workflow_dispatch: # Permite executar manualmente

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar R
        uses: r-lib/actions/setup-r@v2

      - name: Instalar pacotes R necessários
        run: |
          Rscript -e 'install.packages("crypto2", repos="https://cloud.r-project.org")'

      - name: Executar script de download
        run: |
          Rscript R/download_crypto_rankings.R

      - name: Salvar artefatos (opcional)
        uses: actions/upload-artifact@v3
        with:
          name: rankings
          path: DB/CMK/
